name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  auto_size_text: ^3.0.0
  carousel_slider: ^5.1.2
  scrollable_positioned_list: ^0.3.8
  google_fonts: ^8.0.2
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    -  assets/logo/
    -  assets/picture/
    - assets/data/
  
  fonts:
    - family: Rasa
      fonts:
        - asset: assets/fonts/rasa/Rasa-Regular.ttf
        - asset: assets/fonts/rasa/Rasa-Bold.ttf
        - asset: assets/fonts/rasa/Rasa-Medium.ttf
        - asset: assets/fonts/rasa/Rasa-SemiBold.ttf
        - asset: assets/fonts/rasa/Rasa-Light.ttf