name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  auto_size_text: ^3.0.0
  carousel_slider: ^5.1.2
  scrollable_positioned_list: ^0.3.8
  google_fonts: ^8.0.2
  equatable: ^2.0.8
  flutter_thermal_printer: ^2.0.1
  intl: ^0.20.2
  dotted_line: ^3.2.3
  barcode: ^2.2.9
  barcode_widget: ^2.0.4
  hive_ce: ^2.19.3
  flutter_printer_01:
    path: C:\Github\plug-in_printer\flutter_printer_01
  hive_ce_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.11.1
  build_runner: ^2.13.1

flutter:
  uses-material-design: true

  assets:
    -  assets/logo/
    -  assets/picture/
    - assets/data/
  
  fonts:
    - family: Rasa
      fonts:
        - asset: assets/fonts/rasa/Rasa-Regular.ttf
        - asset: assets/fonts/rasa/Rasa-Bold.ttf
        - asset: assets/fonts/rasa/Rasa-Medium.ttf
        - asset: assets/fonts/rasa/Rasa-SemiBold.ttf
        - asset: assets/fonts/rasa/Rasa-Light.ttf