// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_application_1/model/print_history.dart';
import 'package:flutter_application_1/model/print_result.dart';
import 'package:flutter_application_1/model/receipt.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PrinterConfigAdapter());
    registerAdapter(PrintHistoryItemAdapter());
    registerAdapter(ReceiptAdapter());
    registerAdapter(ReceiptItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PrinterConfigAdapter());
    registerAdapter(PrintHistoryItemAdapter());
    registerAdapter(ReceiptAdapter());
    registerAdapter(ReceiptItemAdapter());
  }
}
